### ISSUE TITLE
Standardization native range values

### ISSUE THREAD

**Issue by damianooldoni** [trias-project/unified-checklist#11] opened 2018-09-26 09:55 UTC
After review pipeline, next (final) step will be standardization of vocabularies. While working on producing an unified checklist of alien species of Belgium I noticed that native range assumes values at a variety of levels (country level, continental level, climate level, origin level). While reading data from the following six checklists:
1. Manual of the Alien Plants of Belgium
2. Inventory of alien macroinvertebrates in Flanders, Belgium
3. Checklist of non-native freshwater fishes in Flanders, Belgium
4. Catalogue of the Rust Fungi of Belgium
5. RINSE - Registry of non-native species in the Two Seas region countries (Great Britain, France, Belgium and the Netherlands)
6. RINSE - Pathways and vectors of biological invasions in Northwest Europe

I get the following values:
`Africa`, `Africa (WGSRPD:2)`, `Arctic`, `Asia`, `Australasia (WGSRPD:5)`, `Australia`, `Australia (WGSRPD:50)`, `China`, `cultivated origin`, `East Asia`, `Eastern Europe`, `Europe (WGSRPD:1)`, `hybrid origin`, `Indo-Pacific`, `New Zealand`, `North Africa`, `Northeast Asia`, `Northern America`, `Northern America (WGSRPD:7)`, `pan-American`, `Pantropical`, `Ponto-Caspian`, `South America`, `Southeast Asia`, `Southern America (WGSRPD:8)`, `Southern Europe`, `Southern Hemisphere`, `temperate Asia (WGSRPD:3)`, `Tropical and warm seas`, `tropical Asia (WGSRPD:4)`, `United States`, `West Africa`, `Western Atlantic`.

@peterdesmet: WGSRPD has been conceived specifically for plant distribution. Are there good practice guidelines for distribution of species belonging to other kingdoms? Does an unique controlled vocabulary for all kingdoms? Any other idea about standardization? I don't see immediately a solution. Thanks in advance.

**Comment by peterdesmet** [comment] 2018-11-08 19:50
@qgroom @timadriaens @soniavdh do we and how do we want to standardize **native range** (e.g. Africa) values in the unified checklist?

**Comment by damianooldoni** [comment] 2020-03-31 10:28
See comments of @timadriaens in developing web applications based on unified checklist.
https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/145#issuecomment-606521136.

if we all agree to use 
> WGSRPD for plants and UN geoscheme for animals 

maybe it is worth to write a mapping in a tabular file (csv) and use it in unified.

**Comment by damianooldoni** [comment] 2020-04-01 07:51
I agree with @peterdesmet (https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/145#issuecomment-606554752) about making a decision while standardizing this field.

I can work on it as soon as TrIAS experts decide on it.

**Comment by qgroom** [comment] 2020-04-01 08:09
It's a very difficult, if not practically impossible think to standardize, so if we can squeeze it into "WGSRPD for plants and UN geoscheme for animals" then that's fine for me.

**Comment by peterdesmet** [comment] 2020-04-01 08:11
What do you want to learn from native range? Would _continent_ be sufficient (which I think is mappable) or is that too broad?

**Comment by qgroom** [comment] 2020-04-01 08:22
I guess it is linked to pathways and climate matching, but there are no standard distributions and the more broad you go, then more useless the data becomes. I think this is only useful for a human readable indication and if you want to answer scientific questions you have to go to observation data.

**Comment by damianooldoni** [comment] 2020-04-01 14:36
Thanks @qgroom, @timadriaens and @peterdesmet for your inputs.
Let's say we stick to WGSRPD for plants and UN geoscheme for all other kingdoms.

Two related issues are:
1. uniforming the WGSRPD values as we have level 1 values (e.g. `Australasia (WGSRPD:5)`), level 2 values (e.g. `Australia (WGSRPD:50)`) and level 3 (e.g. Canary Islands (`WGSRPD:21_CNY)`). Sticking to level 1 makes mapping similar to UN geoscheme values. 
2. mapping native range values `cultivated origin`, `hybrid origin`, which I don't find in WGSPRD or UN geoscheme. Maybe solving them at checklist level even? Here some taxonomic information about taxa with these values:
- [taxa_unified_cultivated_origin.txt](https://github.com/trias-project/unified-checklist/files/4415750/taxa_unified_cultivated_origin.txt)
- [taxa_unified_hybrid_origin.txt](https://github.com/trias-project/unified-checklist/files/4415753/taxa_unified_hybrid_origin.txt)

By the way, all taxa in these two files are plants.

**Comment by timadriaens** [comment] 2020-04-01 18:57
@peterdesmet what we learn from it are the major donor regions of alien taxa and how these change in time. Also, we can relate pathways to donor regions and see how these change. 

To do crude climate matching, what we'd use as 'native range' is too coarse, you would need to use something climate related such as Köppen-Geiger, climate envelopes or other (see e.g. [this paper](https://doi.org/10.1016/j.biocon.2014.08.014)). 

An example: in Europe, lots of aquatic plants used to come from markets in Singapore, but that market is shifting to north Africa, which is not only relevant for the alien macrophytes but also for invertebrates hitchhiking on plant material. Potentially these donor regions use other pathways or commodities, have other biosecurity regimes, different propagule pressure etc. Which could have an impact on the aliens that establish in Belgium. Some graphs below to illustrate commonly shown information coming from native range information in checklists (perhaps it is becoming clear now how checklists are very informative provided all information can be combined in a "cube-like" query - which is what I envisaged from the beginning and why I put so much emphasis on the "breakdowns" for the indicators see [this issue](https://github.com/trias-project/indicators/issues/17)):

[Roy et al. 2014](https://doi.org/10.1007/s10530-014-0687-0)
![image](https://user-images.githubusercontent.com/16116743/78175505-46639a00-745b-11ea-8f09-e1537b55f8bd.png)

![image](https://user-images.githubusercontent.com/16116743/78175358-03092b80-745b-11ea-8fc9-30d42386dc0c.png)

![image](https://user-images.githubusercontent.com/16116743/78175539-54191f80-745b-11ea-91b2-744177595079.png)

**Comment by timadriaens** [comment] 2020-04-01 19:07
another example from [Gallardo et al. 2014](https://doi.org/10.1007/s10530-015-0986-0) where they have combined native range with an impact assessment (in other words: where are the most problematic invaders coming from). 

This is also interesting from a **policy perspective**: we have species native to Europe but alien to Belgium, which need different policy regime (for instance, they should be on a national list of invasive alien species and cannot figure on the Union List of the Regulation).

![image](https://user-images.githubusercontent.com/16116743/78176163-5cbe2580-745c-11ea-9ecf-8974ee9fe79c.png)

**Comment by timadriaens** [comment] 2020-04-01 19:25
@damianooldoni @qgroom I believe terms like **cultivated origin** and **hybrid origin** do not belong in native range but should be mapped onto **dwc:establishmentMeans**? 

Hybrid origin = when it is a "spontaneous hybrid" (e.g.  _Reynoutria bohemica_, _Oxalis ×uittienii_)
Cultivated origin = artificial hybrid (e.g. the famous example _Spiranthes cernua x odorata_)

**Comment by peterdesmet** [comment] 2020-04-02 07:57
@timadriaens all the charts you show use broad regions (like continents), which is why I'm wondering if https://en.wikipedia.org/wiki/United_Nations_geoscheme could work (which includes those broad regions)

**Comment by timadriaens** [comment] 2020-04-02 13:02
for me that is ok (but it's more detailed than the Botanical continents in the [World Geographical Scheme for Recording Plant Distributions](https://en.wikipedia.org/wiki/World_Geographical_Scheme_for_Recording_Plant_Distributions#Levels) as you can see below). 

For the bird checklist and the add hoc we also consequently followed UN geoscheme.

![image](https://user-images.githubusercontent.com/16116743/78252309-efa99f00-74f2-11ea-9673-9b496dd3f8ba.png)

![image](https://user-images.githubusercontent.com/16116743/78251757-1915fb00-74f2-11ea-9b98-7149c03c491e.png)

**Comment by peterdesmet** [comment] 2020-04-03 09:22
I've created a [spreadsheet with all 150 native range values](https://docs.google.com/spreadsheets/d/1I8jLNoTWCl0ufZVhCOBW81LgtOeBLOOfUSV2gOFlkBc/edit?usp=sharing), and tried to map them to UN Geoscheme. Most mappings make the area broader (as expected), but I was able to quite easily map 3805 of the 4109 records (= 93%). The hardest one is Asia-temperate (see drawings above). Are we ok moving forward with the UN Geoscheme?

**Comment by timadriaens** [comment] 2020-04-03 13:12
That's great an a huge leap forward @peterdesmet ! I will take a look at it and see if I can map some more. We do need something else for the marine species, would it be possible to check how standardized this is in WRIMS and if we could use the same for the unified?

**Comment by peterdesmet** [comment] 2020-04-03 14:07
No, that information is not included in the wrims-checklist. Information we have in there are:

type | example | remark
--- | --- | ---
Introduced species abundance | in French part of the Bay of Biscay (Marine Region) : Common to dominant | seems to be about non-native range
Introduced species impact | in French part of the Celtic Sea (Marine Region) : Consumes native species (predator or herbivore) | not about native range
Introduced species management | in Canadian part of the Gulf of St-Lawrence (Marine Region) : yes | not about native range
Introduced species population trend | in Romanian part of the Black Sea : Reproduction here is unlikely, because of the low salinity (~ 18 PSU) (Micu et a ... | not about native range
Introduced species remark | In Kenyan part of the Indian Ocean : The burrowing activity of Procambarus clarkii can damage crops, such as rice and taro, ... | not about native range
Introduced species vector dispersal | in Denmark (Nation) : Fisheries: accidental with deliberate translocations of fish or shellfish | seems to be pathway information, but per region and not standardized

**Comment by timadriaens** [comment] 2020-04-08 08:37
@peterdesmet native range information is definitely in WRiMS in the distribution (and it's the basis on which they selected the subset of species from WoRMS to put in WRiMS), here's an example of Mnemiopsis leidyi so it should be in their checklist and if not I feel VLIZ should provide it:

in WoRMS
<img width="537" alt="2020-04-08 10_29_40-WoRMS - World Register of Marine Species - Mnemiopsis leidyi A  Agassiz, 1865" src="https://user-images.githubusercontent.com/16116743/78762910-cb334400-7984-11ea-878f-5be0afe7ad04.png">


In WRiMS
<img width="229" alt="b_2020-04-08 10_33_22-World Register of Introduced Marine Species (WRiMS) - Mnemiopsis leidyi A  Agass" src="https://user-images.githubusercontent.com/16116743/78762791-a3dc7700-7984-11ea-94f1-cf43f24dff48.png">

**Comment by timadriaens** [comment] 2020-04-08 08:54
questions from @peterdesmet regarding standardizing native range:

- do we want it included in the unified checklist then, not as a preprocessing for the indicators?
- do we want it instead of the checklist native range, not in addition to? (i.e. only one type of native range value)

Some ideas:

1. *Native range* is not in GRIIS (and our unified is GRIIS, no?) - only *origin* (alien/native/cryptogenic) is, but used for the indicators. So for me it is fine in the preprocessing - but also useful in the unified no?
2. We want it in addition to, because the checklist itself mostly contains more detailed information (see my comments [here](https://github.com/inbo/reporting-rshiny-grofwildjacht/issues/145#issuecomment-606521136)). So for instance, we know the land planarian _Obama nungara_ is coming from Argentina, and the paper with the genetic analysis is in the checklist but for the indicators South America is enough. We should then strive to keep both levels of information no?

In fact, I think the mapping is in theory best done by the checklist owners as they know the species best and are best placed to do this sort of mapping. But we know it's utopia to expect this from without offering them proper IT tools to manage their checklist right...

**Comment by peterdesmet** [comment] 2020-04-09 09:55
Summary of discussion with @timadriaens 

- Combining native range _distributions_ from an additional dataset (WoRMS) into the unified checklist is a completely different workflow and one we will not tackle
- The unified checklist acts as a source for GRIIS, but there is not problem including information we find useful (like native range)
- Generalizing native range info at source checklist level is not a good idea (unless it is obvious): we will loose more precise information and it cannot be expected of all checklist authors
- **We will standardized/generalized native range information in the unified checklist**, so that it is readily available for the indicators
- We decided **not to retain the source native range information** in the unified checklist (in addition to the standardized info): it is available in the source checklist and the goal is to provide unified readily available information
- For the 7% of data we currently cannot map to UN Geoscheme we will leave it empty, rather than having original values cluttering the standardized info
- @timadriaens will take a stab at the spreadsheet, after which I will include this in the unified processing.

**Comment by peterdesmet** [comment] 2020-04-10 14:31
The code is now written to map native_range:

https://github.com/trias-project/unified-checklist/blob/90e4808ec1bbcd1453eff0498047243cab81f6f0/src/5_unify_information.Rmd#L346-L352

but the spreadsheet should be completed (e.g. by @timadriaens or @qgroom) so I can incorporate all of it before I republish and close this issue.

**Comment by peterdesmet** [comment] 2020-04-10 15:20
I've now completed the checklist. Would like to get some feedback on the "remarks" column.

**Comment by peterdesmet** [comment] 2020-04-15 11:15
This is now solved 92ccb3c6ff96a67b2ef697f80fc9538d5e2daebc and published in the unified checklist.

**Closed by peterdesmet** 2020-04-15 11:15 UTC
Labels: standardization
